# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# jou can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MaxxAir Fan Installation Guides
email: corey@maxxairfaninstall.com
description: >- # this means to ignore newlines until "baseurl:"
  Looking to install your Maxx Air Fan to your van? Doing #vanlife? You should be able to find help here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxxairfaninstall.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
